# Generated by Django 2.2.1 on 2019-06-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolucao',
            field=models.ManyToManyField(blank=True, null=True, to='pokedex.Pokemon'),
        ),
    ]
