# Generated by Django 2.2.1 on 2019-05-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20190502_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='fk_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pokedex.Tipo'),
        ),
    ]
