# Generated by Django 2.2.1 on 2019-05-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_fk_habilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao_tipo', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
    ]
