# Generated by Django 2.2.1 on 2019-05-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='fk_tipo',
            field=models.ManyToManyField(to='pokedex.Tipo'),
        ),
    ]
