# Generated by Django 2.2.1 on 2019-05-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20190502_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='fk_categoria',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='fk_categoria',
            field=models.ManyToManyField(to='pokedex.Tipo'),
        ),
    ]
