# Generated by Django 2.2.1 on 2019-05-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_auto_20190502_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='fk_categoria',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
